# ── ejecutar.ps1 ─────────────────────────────────────────────────────────────
# Main ETL script. Run from the dashboard button or directly in the terminal
# to refresh the P&G and Balance Sheet data files for the dashboard.
# ─────────────────────────────────────────────────────────────────────────────

. "$PSScriptRoot\scripts\procesar_pyg.ps1"
. "$PSScriptRoot\scripts\procesar_balance.ps1"

Write-Host "=== retail-etl Alternativas El Descuento ===" -ForegroundColor Cyan

# ── STEP 1: Read P&G ─────────────────────────────────────────────────────────
Write-Host "[PASO 1/5] Procesando Estado de Resultados..." -ForegroundColor Cyan
$pyg = ProcessAllPyG

if ($pyg.Count -eq 0) {
    Write-Host "[ERROR] No se pudieron leer datos del P&G. Verifica config/rutas.ps1" -ForegroundColor Red
    exit 1
}

Write-Host "[PASO 2/5] Construyendo datos del P&G ($($pyg.Count) meses)..." -ForegroundColor Cyan

$jsLines = [System.Collections.Generic.List[string]]::new()
foreach ($d in $pyg) {
    $jsLines.Add(
        "    { periodo:`"$($d.periodo)`", mes:`"$($d.mes)`"," +
        " ventas:$($d.ventas), costo_ventas:$($d.costo_ventas)," +
        " margen_pesos:$($d.margen_pesos), margen_pct:$($d.margen_pct)," +
        " personal:$($d.personal), arriendo:$($d.arriendo)," +
        " servicios:$($d.servicios), honorarios:$($d.honorarios)," +
        " impuestos:$($d.impuestos), gastos_ventas:$($d.gastos_ventas)," +
        " total_gastos:$($d.total_gastos), resultado:$($d.resultado) }"
    )
}

$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
$body      = $jsLines -join ",`n"

Write-Host "[PASO 3/5] Escribiendo data.js..." -ForegroundColor Cyan

$out = [System.Collections.Generic.List[string]]::new()
$out.Add("// Auto-generated by retail-etl/ejecutar.ps1")
$out.Add("// Source: Estado de Resultados Comparativo Mes a Mes (2024-2026)")
$out.Add("// Last updated: $timestamp")
$out.Add("// DO NOT edit manually")
$out.Add("")
$out.Add("window.DASHBOARD_DATA = {")
$out.Add("  metadata: {")
$out.Add("    generado: `"$timestamp`",")
$out.Add("    fuente: `"Estado de Resultados Comparativo Mes a Mes`",")
$out.Add("    meses_procesados: $($pyg.Count)")
$out.Add("  },")
$out.Add("  ventas_mensual: [")
$out.Add($body)
$out.Add("  ]")
$out.Add("};")
$pygContent = $out -join [System.Environment]::NewLine

$outPath = $script:CONFIG.Output_Dashboard
$outDir  = Split-Path $outPath
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Force -Path $outDir | Out-Null }
[System.IO.File]::WriteAllText($outPath, $pygContent, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "  P&G OK - $($pyg.Count) meses -> $outPath" -ForegroundColor Green

# ── STEP 4: Read Balance Sheet ────────────────────────────────────────────────
Write-Host "[PASO 4/5] Procesando Balance General..." -ForegroundColor Cyan
$bal = ProcessAllBalances

if ($bal.Count -eq 0) {
    Write-Host "  ADVERTENCIA: No se pudo leer el Balance General." -ForegroundColor Yellow
} else {
    $balLines = [System.Collections.Generic.List[string]]::new()
    foreach ($d in $bal) {
        $balLines.Add(
            "    { mes:`"$($d.mes)`"," +
            " disponible:$($d.disponible), cxc:$($d.cxc), deudores:$($d.deudores)," +
            " inventarios:$($d.inventarios), activo_cte:$($d.activo_cte), total_activo:$($d.total_activo)," +
            " oblig_fin:$($d.oblig_fin), proveedores:$($d.proveedores), cxp_otros:$($d.cxp_otros)," +
            " pasivo_cte:$($d.pasivo_cte), total_pasivo:$($d.total_pasivo), patrimonio:$($d.patrimonio) }"
        )
    }
    $balBody = $balLines -join ",`n"

    Write-Host "[PASO 5/5] Escribiendo data_balance.js..." -ForegroundColor Cyan

    $balOut = [System.Collections.Generic.List[string]]::new()
    $balOut.Add("// Auto-generated by retail-etl/ejecutar.ps1")
    $balOut.Add("// Source: Balance General Comparativo (2024-2026)")
    $balOut.Add("// Last updated: $timestamp")
    $balOut.Add("// DO NOT edit manually")
    $balOut.Add("")
    $balOut.Add("window.BALANCE_DATA = {")
    $balOut.Add("  metadata: {")
    $balOut.Add("    generado: `"$timestamp`",")
    $balOut.Add("    fuente: `"Balance General Comparativo`",")
    $balOut.Add("    meses_procesados: $($bal.Count)")
    $balOut.Add("  },")
    $balOut.Add("  mensual: [")
    $balOut.Add($balBody)
    $balOut.Add("  ]")
    $balOut.Add("};")
    $balContent = $balOut -join [System.Environment]::NewLine

    $outBal = $script:CONFIG.Output_Balance_Dashboard
    [System.IO.File]::WriteAllText($outBal, $balContent, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "  Balance OK - $($bal.Count) meses -> $outBal" -ForegroundColor Green
}

Write-Host "[COMPLETADO] P&G=$($pyg.Count) meses. Balance=$($bal.Count) meses." -ForegroundColor Green
